### ISSUE TITLE
Create theme for Visual Studio Code 

### ISSUE THREAD

**Issue by fabriciorissetto** [zenorocha/dracula-theme#106]
Add support to **Visual Studio Code** is the new multiplatform text editor from Microsoft that can be used to develop with **NodeJS**, C++, ASP.NET, PHP, Python, Java.

https://code.visualstudio.com/

**Comment by zenorocha** [comment]
As said in the README:

> **"Are you going to support editor X?"**

>  I hope so, but I need your help to accomplish that. Since you're using editor X you're probably much more expert on it than me. So feel free to send a pull request based on the Color Palette below.

I love the idea of having a Visual Studio theme and look forward to your pull request.

**Comment by zenorocha** [comment]
Just found this one https://studiostyl.es/schemes/dracula-atom could you confirm if it works @fabriciorissetto?

**Comment by zenorocha** [comment]
Seems like it Visual Studio Code supports [tmTheme](https://github.com/zenorocha/dracula-theme/blob/master/Dracula.tmTheme)! https://code.visualstudio.com/docs/customization/themes

**Comment by Ulthes** [comment]
Yeah, all you have to do is run it through yeoman generator (more info here: https://code.visualstudio.com/docs/customization/overview). I think I'll make a pull request today/tomorrow with generated theme :).

**Comment by zenorocha** [comment]
Please do @Ulthes! :ghost:
