### ISSUE TITLE
Dracula theme doesn't work with Xcode 7

### ISSUE THREAD

**Issue by shadowsyntax** [zenorocha/dracula-theme#113]
I followed the instructions @ your the project sites URL but can't get to theme to work with Xcode 7. The Dracula theme basically isn't showing in the preference page

**Comment by zenorocha** [comment]
Hey @jordanbrown, can you take a look?

**Comment by arg20** [comment]
+1

**Comment by arg20** [comment]
@shadowsyntax @zenorocha @jordanbrown guys to me it works now, I'm not sure if it was the fact that I rebooted my computer or the IDE, I think it's when I restarted my macbook but you may want to give that a try.

**Comment by Elshad** [comment]
Restarting of Xcode helps

**Comment by jimmyDunne** [comment]
I am getting the same behavior. When I use symbolic links, Xcode 7 does not recognize. I tested (symbolic links) with some different themes, so this is Xcode 7 specific.  Reboot/restart has no effect

**Comment by zenorocha** [comment]
Seems to be working here too. Feel free to leave a comment if this problem is still happening or open a pull request with instructions on how to fix it. Thanks!

**Comment by rusenask** [comment]
Just in case someone else bumps into this, for some reason symlink didn't work for me too. Copying 
`cp Dracula.dvtcolortheme  ~/Library/Developer/Xcode/UserData/FontAndColorThemes/` solved the problem.
