### ISSUE TITLE
Better support for python highlight in emacs

### ISSUE THREAD

**Issue by tkaczu** [zenorocha/dracula-theme#115]
Please give additional love for python syntax highlighting. I really like dracula theme for my Iterm/terminal and I used it in my spacemacs but the highlighting for python (especially django templates and models) are not so colorful. 
Could You work a bit more on it?
Thank You in advance.

**Comment by zenorocha** [comment]
Hey @tkaczu, feel free to submit a pull request with your suggestions.

/cc @film42

**Comment by film42** [comment]
Spacemacs add a lot of add-ons, so maybe one of them is messing with the theme? Using standard `python-mode`, the theme looks pretty good.

![193125](https://cloud.githubusercontent.com/assets/1043908/11052771/82dc41c4-8718-11e5-8243-2844e14e324b.png)
(Sorry, monosnap does some weird compression on retina macbooks).

@tkaczu I think we should consider this good, but you can always add mode specific color highlighting to the theme file and open a PR with those changes. I'd love to see this theme mature a bit more :)

**Comment by tkaczu** [comment]
Ok, Guys I will add some more syntax highlighting in the next two or three weeks. 
The thing which I really want to add is coloring variable name during initalization etc. I will use spacemacs-dark theme as a reference for adding missing coloring.

**Comment by zenorocha** [comment]
That would be awesome. I'll close this one for now but feel free to send a pull request guys ;)
