### ISSUE TITLE
Running Emacs in iTerm2 support?

### ISSUE THREAD

**Issue by jonathanchu** [zenorocha/dracula-theme#116]
Hey! Great theme! :)

I just tried running this in Emacs in iTerm2 and it seems the theme does not render correctly.  I have `xterm-256color` set, so I'm not sure if the color is not degrading well or if this is a bug.  

I'm on Emacs v24.5.1 (via homebrew), iTerm2 v2.1.4, and OS X El Capitan v10.11.1.  Any help or advice on this is appreciated, thanks!

<img width="822" alt="screenshot 2015-11-09 15 48 23" src="https://cloud.githubusercontent.com/assets/66164/11046159/b8a7f11e-86f9-11e5-86f0-074cfb93392c.png">

**Comment by zenorocha** [comment]
@film42 @avelino any ideas?

**Comment by film42** [comment]
This problem was mentioned in the [Emacs Love PR](https://github.com/zenorocha/dracula-theme/pull/98#issuecomment-152603771). There's not a ton we can do about terminal emacs until emacs supports True Color (24bit RGB) values.

Looks like someone put a patch together (though the thread is quite old): http://emacs.1067599.n5.nabble.com/RFC-Add-tty-True-Color-support-td299962.html

**Comment by jonathanchu** [comment]
@film42 thanks for response and explanation - I appreciate the input! :)

For this emacs theme, do you think there could be a work-around similar to what emacs solarized proposes?  https://github.com/sellout/emacs-color-theme-solarized#important-note-for-terminal-users

I'm not really sure what to do there or if that would be a viable solution for this.

Thanks!

**Comment by 121onto** [comment]
I got the theme to work by installing emacs with homebrew:

```
brew install --srgb --cocoa --HEAD
```

**Comment by 121onto** [comment]
Update:

I have this working now.  Here is what I did.

1. Uninstall emacs and download source:

 ```{bash}
 brew uninstall emacs
 brew unlink emacs
 cd ~/temp
 git clone https://github.com/emacs-mirror/emacs.git
 cd emacs
 ```

2. Install true color patch available [here](https://gist.github.com/choppsv1/73d51cedd3e8ec72e1c1)

 ```{bash}
 git reset --hard "emacs-24.3"
 curl -O https://gist.githubusercontent.com/choppsv1/73d51cedd3e8ec72e1c1/raw/e54ef720cb55ac539adefde9bc87a14ea05b0b99/emacs-24.3-24bit.diff
 patch -p1 < emacs-24.3-24bit.diff
```

3. Install emacs from source:

 ```{bash}
 ./autogen.sh
 ./configure \
 --prefix=/usr/local/Cellar/emacs-24-with-24bit-colors/1.0 \
 --enable-locallisppath=/usr/local/share/emacs/site-lisp \
 --infodir=/usr/local/Cellar/emacs-24-with-24bit-colors/1.0/share/info/emacs \
 --with-xml2 \
 --without-dbus \
 --without-gnutls \
 --with-ns \
 --disable-ns-self-contained
 make
 make install
 cp -R nextstep/Emacs.app /usr/local/Cellar/emacs-24-with-24bit-colors/1.0/
 chmod 0555 /usr/local/Cellar/emacs-24-with-24bit-colors/1.0/Emacs.app
 printf '#!/bin/bash\nexec /usr/local/Cellar/emacs-24-with-24bit-colors/1.0/Emacs.app/Contents/MacOS/Emacs "$@"' >> /usr/local/Cellar/emacs-24-with-24bit-colors/1.0/bin/emacs
 chmod 0555 /usr/local/Cellar/emacs-24-with-24bit-colors/1.0/bin/emacs
 ln -s /usr/local/Cellar/emacs-24-with-24bit-colors/1.0/bin/emacs /usr/local/bin/emacs
 ```

One issue, the patch is written for Emacs 24.3, it does not seem to work with more recent versions.

**Comment by film42** [comment]
Interesting. I'll try compiling the patch in later tonight to see what I can come up with. This isn't really related to this project, because it would be strange to ask users to patch their emacs for a theme, but it sure is interesting :)

**Comment by jonathanchu** [comment]
@121onto cheers, thanks for the detailed writeup!  I'll give this a try too and see how it goes.  :smile: :+1:

**Comment by film42** [comment]
Looks like @choppsv1 also made a patch for emacs 24.5: https://gist.github.com/choppsv1/e8198df70cb1778b04d6

I followed the sam configure flags as @121onto , only with the emacs 24.5 branch.

I then set `export ITERM_24BIT=1` to enable it in my shell.

At first I was getting 24 bit color, but iTerm was failing to render the text, so I searched around and someone said that to get vim working with 24 bit colors and iTerm, you need to download the latest [nightly build](https://iterm2.com/nightly/latest). After that, things worked great :).

![image](https://cloud.githubusercontent.com/assets/1043908/11649267/7c017fc6-9d3a-11e5-9f34-2cc13e058ad2.png)

**Comment by 121onto** [comment]
@film42 thank you!  

So much effort, and the second we upgrade it all goes away.  I am in touch with the emacs dev team and will point this out to them.  Would be great to get true color support in the next release.

**Comment by cstrahan** [comment]
@121onto Have you heard anything from the emacs developers? I've contacted @ruediger to see if he's still working on it. If 24-bit color support isn't currently underway, it's something that I'd be willing to take on and contribute upstream to emacs.

**Comment by choppsv1** [comment]
FWIW, I also have a homebrew tap setup that builds the patched emacs which is a lot easier than doing it by hand. :) The tap is choppsv1/term24/emacs.
