### ISSUE TITLE
Vundle doesn't work

### ISSUE THREAD

**Issue by adolphenom** [zenorocha/dracula-theme#120]
I try to install the theme using vim in Mac (I'll try at home with ArchLinux) but it doesn't move the color scheme at colors folder.

I follow the instructions literally.

It works with other plugins, thought.

**Comment by ribeiroevandro** [comment]
I had the same problem, but in my case it moves, but does not apply the colors, leaving a ghastly gray, as seen in the image below.
![screen shot 2016-01-19 at 15 48 08](https://cloud.githubusercontent.com/assets/943553/12427191/efdaef26-bec4-11e5-9928-e632a67f2ebe.png)

**Comment by dciccale** [comment]
if you are talking about vundle plugin manager..i use it like this:

```viml
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/Vundle.vim'

Plugin 'zenorocha/dracula-theme',{'rtp':'vim/'}
```

and it works.

do you have other themes installed via vundle that are working? maybe we could check those and see what's the diff, wdyt?

**Comment by ribeiroevandro** [comment]
No, I do not have other installed themes, but I think it was settings problems I will try to redo and see if I can solve this problem.

**Comment by nesl247** [comment]
Are you guys still having this issue?

**Comment by nesl247** [comment]
Going to close this for now. Please feel free to reopen if you are still having the issue.

**Comment by adolphenom** [comment]
I didn't try again since nobody replied to this issue until january. I didn't know if someone fixed it, sorry.

**Comment by nesl247** [comment]
@adolphenom If you are still having the issue, please file a new bug at https://github.com/dracula/vim.

Again, sorry for the delayed reply.
