### ISSUE TITLE
Not readeble text in startup vim

### ISSUE THREAD

**Issue by t0kieu** [zenorocha/dracula-theme#122]
Hi,
I found bug, at startup vim some texts aren't readable. Texts has wrong color used, see attachment.
Please fix it.
![screen shot 2015-12-15 at 15 11 28](https://cloud.githubusercontent.com/assets/832781/11812911/efd323c8-a33e-11e5-824d-40e072c66941.png)

**Comment by dciccale** [comment]
add this to your `.vimrc` and disable that screen, problem solved :dancer: 

```viml
set shortmess=I
```

however it would be nice having it fixed in the theme...

**Comment by zenorocha** [comment]
Could you send a pull reuqest @dciccale?

**Comment by dciccale** [comment]
@zenorocha hmm.. I think this is personal configuration and shouldn't be included in the theme. the best way to solve this would be knowing the highlight group that is targeting those texts and change their `fg` color.

**Comment by zenorocha** [comment]
Thanks a lot for clarifying that @dciccale ;D
