### ISSUE TITLE
Make the color space explicit

### ISSUE THREAD

**Issue by toogy** [zenorocha/dracula-theme#132]
I'm using [termite](https://github.com/thestinger/termite/) as a terminal (which is awesome BTW) and I would like to add **dracula** to my theme collection.

Here is what the configuration looks like with the example of **base16-mocha**
```
[colors]
# Base16 Mocha
# Scheme: Chris Kempson (http://chriskempson.com)

foreground      = #d0c8c6
foreground_bold = #d0c8c6
cursor          = #3de8ff
background      = #3B3228

# 16 color space
color0  = #3B3228
color1  = #cb6077
color2  = #beb55b
color3  = #f4bc87
color4  = #8ab3b5
color5  = #a89bb9
color6  = #7bbda4
color7  = #d0c8c6
color8  = #7e705a
color9  = #cb6077
color10 = #beb55b
color11 = #f4bc87
color12 = #8ab3b5
color13 = #a89bb9
color14 = #7bbda4
color15 = #f5eeeb

# 256 color space
color16 = #d28b71
color17 = #bb9584
color18 = #534636
color19 = #645240
color20 = #b8afad
color21 = #e9e1dd
```

But from the configuration of **dracula** for other programs *(Terminal, vim, emacs...)* and even this repository's `README` I am not able to transpose them to a basic 16 color space.

Could you help me please? :smile:

**Comment by zenorocha** [comment]
Hey @toogy, sorry for taking so long to reply.

Unfortunately, I don't have a solution for this issue :/
