### ISSUE TITLE
Theme

### ISSUE THREAD

**Issue by oefterdal** [zenorocha/dracula-theme#133]
Any tips on a good companion Sublime Text theme ?

**Comment by film42** [comment]
This is a sublime text theme. You can install it via package control.

**Comment by oefterdal** [comment]
Maybe I wasn't so clear, I can only find a Color Scheme for Sublime Text. Not a application theme.
Or am I missing something here ?

"color_scheme": "Packages/Dracula Color Scheme/Dracula.tmTheme",

**Comment by film42** [comment]
I see what you mean. There isn't a dracula sublime UI theme, but we accept pull requests :).

I'm going to leave this issue closed as it's somewhat off topic (vague feature request/ tip request), but please, we love love love contributions.
