### ISSUE TITLE
Slack theme does not match preview screenshot

### ISSUE THREAD

**Issue by mattnedrich** [zenorocha/dracula-theme#139]
The slack theme preview screenshot shows the current channel highlighted in pink. This does not match what I observe when I install the theme. I imagine this is the Menu BG Hover color.

![image](https://cloud.githubusercontent.com/assets/4796480/13374462/6bbe8632-dd53-11e5-8584-727010ca81d6.png)

**Comment by zenorocha** [comment]
Everything looks fine from here.

<img width="1552" alt="screen shot 2016-04-30 at 10 25 41 am" src="https://cloud.githubusercontent.com/assets/398893/14937495/e84195dc-0ebd-11e6-848e-cd05585a800e.png">

Could you please send a screenshot from yours? Thanks!

**Comment by heinst** [comment]
Wouldn't close this quite yet. Have the same issue, not by my computer but my theme was not as pictured either. The channel highlighting is not pink. It's a grey color.

**Comment by heinst** [comment]
`282A36,#44475A,#44475A,#8BE9FD,#6272A4,#FFFFFF,#50FA7B,#FF5555` is the code for the theme on the website. This does not match your theme codes. Can you update the website with the correct codes??

**Comment by heinst** [comment]
@zenorocha reopening because your codes did not match the ones on the website

**Comment by zenorocha** [comment]
Yes, I can do that.

**Comment by nesl247** [comment]
I've gone ahead and submitted 2 PRs to fix this based on the screenshot from @zenorocha .

**Comment by heinst** [comment]
@nesl247 thanks!
