### ISSUE TITLE
Unreadable commit window in Textmate

### ISSUE THREAD

**Issue by coccoinomane** [zenorocha/dracula-theme#142]
Hello,

First of all, thank you for making available your very cool theme!

I run Dracula on Textmate v2.0-beta.8.5 on Os X 10.11.3 El Capitan. When I commit some modifications with Git, Textmate shows this commit window:

<img width="548" alt="textmate commit window" src="https://cloud.githubusercontent.com/assets/3920436/13381802/fb9a8852-de64-11e5-9b61-beb2d6dfdd99.png">

The text for the new & modified files is unreadable due to the background color being so similar to the text color.

Thank you for your attention,
Guido

**Comment by zenorocha** [comment]
Hey @coccoinomane, thanks for reporting!

We do not have current maintainers for the Textmate theme so feel free to send a pull request.
