### ISSUE TITLE
Background color in Atom Zen

### ISSUE THREAD

**Issue by grntartaglia** [zenorocha/dracula-theme#144]
Really love the theme, but I have some problems using it with Zen in Atom. I get this weird white background.

![captura de tela 2016-03-07 as 17 47 29](https://cloud.githubusercontent.com/assets/5912184/13582785/f73c1f2c-e48c-11e5-881a-78def1bfba03.png)

Zen plugin: [defunkt/zen](https://github.com/defunkt/zen)

**Comment by zenorocha** [comment]
Merged at #145
