### ISSUE TITLE
Tabs color on One Dark ui theme

### ISSUE THREAD

**Issue by ManoloPina** [zenorocha/dracula-theme#146]
The tabs using One Dark theme are contrasting to much, such as the color out of the editor. Like the image bellow:
![captura de tela 2016-03-15 as 11 05 56](https://cloud.githubusercontent.com/assets/3810254/13778592/993e915e-ea6b-11e5-9832-20f677041207.png)

**Comment by zenorocha** [comment]
Thanks for reporting @ManoloPina, feel free to send a PR.
