### ISSUE TITLE
Maintainer needed

### ISSUE THREAD

**Issue by zenorocha** [zenorocha/dracula-theme#149]
There's a really vibrant community around Dracula. Many new themes have been submitted but I'm not finding the time to review them all. Is there anybody interested in becoming the head maintainer of this project?

**Comment by JimmyMultani** [comment]
I don't know about being the head, but I would gladly help maintain the Atom portion of this project.

**Comment by zenorocha** [comment]
Awesome! Thanks @JimmyMultani ;)

**Comment by heinst** [comment]
I would be interested in maintaining the whole thing

**Comment by jacksaunders** [comment]
@zenorocha i will happily help out with PR reviews etc with @JimmyMultani

**Comment by zenorocha** [comment]
Awesome! Feel free to start reviewing and merging the new themes as well ;)

**Comment by zenorocha** [comment]
Inspired by your commitment, I decided to buy the [draculatheme.com](https://draculatheme.com) domain and rewrite the site so you can edit more easily.

Check the [site branch](https://github.com/zenorocha/dracula-theme/tree/site) and let me know what you think ;D

**Comment by zenorocha** [comment]
> cc'ing all the contributors @Ulthes @film42 @quagliato @felipekm @jordanbrown @nuxlli @oswaldoacauan @vagnervjs @ramonmcros @epidemicz @JimmyMultani @jacksaunders @heinst @almirfilho

**Comment by jacksaunders** [comment]
Awesome 😎

-- 
Jack Saunders
Sent with Airmail

On 6 May 2016 at 11:08:41, Zeno Rocha (notifications@github.com) wrote:

cc'ing all the contributors @Ulthes @film42 @quagliato @felipekm @jordanbrown @nuxlli @oswaldoacauan @vagnervjs @ramonmcros @epidemicz @JimmyMultani @jacksaunders @hei nst @almirfilho

**Comment by quagliato** [comment]
Slack theme is pretty easy to maintain. I'm surfing in free time, but I'll keep an eye on it. :)

**Comment by joaoevangelista** [comment]
I can help @cbracco with JetBrains theme too!

**Comment by cbracco** [comment]
@joaoevangelista I’d actually prefer to make you the sole maintainer of the JetBrains theme if you want it (@zenorocha can you make that happen?)! You did a bulk of the work on cleaning up the theme, I was just the instigator. 😄  

@zenorocha I’d be cool with maintaining the icons for each (as talked about in #160).

**Comment by zenorocha** [comment]
That's perfect. Thanks @joaoevangelista @cbracco.

**Comment by joaoevangelista** [comment]
@cbracco Sure, no problem at all!
