### ISSUE TITLE
Highlight area in vim is not that clear.

### ISSUE THREAD

**Issue by gujiaxi** [zenorocha/dracula-theme#156]
As the screenshot below shows, I select line 13 to 18 in `VISUAL MODE` but it is not that distinct.
![_20160507104532](https://cloud.githubusercontent.com/assets/1433945/15089872/03b5c710-1441-11e6-9091-1cdfd4b37c19.png)

**Comment by moistrot** [comment]
same as me

**Comment by heinst** [comment]
This has nothing to do with the vim color palette, but your own terminal highlight preference. On Mac you can go to `Terminal > Preferences > Profiles > Select your Default theme > Click the colored box to the left of "Selection" and select a different color`. Linux is a different story and not too sure how to change it there, maybe someone else can help out.

**Comment by ashchan** [comment]
@heinst Changing Selection color from Terminal highlight preferences only changes the highlight color for Terminal, under Vim the visual mode selection still uses the mentioned 'not distinct' color.

**Comment by heinst** [comment]
I have no such issue

**Comment by ashchan** [comment]
@gujiaxi @moistrot 

As a quick dirty work around, we can add a line like this below `color dracula`:

    hi Visual ctermfg=NONE ctermbg=22 cterm=NONE guifg=NONE guibg=#005f00 gui=NONE

Note in this example I use a deep green.

**Comment by heinst** [comment]
You are welcome to open up a pr with a Dracula highlight color :)

**Comment by ashchan** [comment]
@heinst I'll experimenting themes for other editors to see if the current highlight is such by purpose. Thank you!
