### ISSUE TITLE
Add issue and pull request templates

### ISSUE THREAD

**Issue by zenorocha** [zenorocha/dracula-theme#158]
This will help with reviewing bug fixes and adding new themes.

**Comment by zenorocha** [comment]
Would love to hear your thoughts about this @film42 @heinst @JimmyMultani @jacksaunders

**Comment by heinst** [comment]
Agreed. That will save you a lot of repetitive comments!

**Comment by JimmyMultani** [comment]
Makes sense to me. :)

**Comment by jacksaunders** [comment]
Yea sounds like a great idea
