### ISSUE TITLE
Move dracula to an organization with separate repositories

### ISSUE THREAD

**Issue by nesl247** [zenorocha/dracula-theme#163]
This is something I've thought about for a while. The question is wouldn't it be better if an organization was created for dracula-theme, with each repository being a single application and/or theme? This would make it much, much easier to work with plugin managers such as Fundle, Fisherman, Oh-My-Fish, Oh-My-Zsh, APM (Atom).

It would also make the directory structure less confusing. For example, I had no idea where the Atom theme was because I was looking for an Atom directory. It's kind of hackish to have the repository try to support all the plugin managers for the different themes in the same repository.

Another benefit is the site can be maintained in a separate repository instead of a branch. This makes it much easier to submit PRs a bit, and keeps the list a bit more separated for them as well.

**Comment by jacksaunders** [comment]
@nesl247 Very much agree, was one of my bug bears when starting out using Dracula. Think this is a good solution

**Comment by joaoevangelista** [comment]
Also is better for maintaining several editors with different maintainers

**Comment by JimmyMultani** [comment]
I'm not against this either.

**Comment by nesl247** [comment]
Hadn't thought of it before, but this will also make versioning a lot more useful. Now we will really be able to have changelogs and versions per application/editor.

**Comment by jacksaunders** [comment]
Seems like a no brainer then, how do we go about moving this forward

**Comment by nesl247** [comment]
We would need @zenorocha to create an organization, and move this repository to it.

After that, the next steps would be to create a repository for each product that is supported, and added the corresponding maintainer to it. Once that is done, all of the code needs to be copied over. If we want to keep history, I think https://github.com/dflydev/git-subsplit might help unless someone knows another way.

The site also needs to be moved to it's own repository as organizations use a repository rather than a project for the hosted sites.

Once the move is done, we should create a release for each repository with whatever the current release number is. We also need to create a README.md for every repository. This might be a good way to build the site as well. The site builder could just use the README.md for each repository instead of having to duplicate the information.

Once a release is created for each repository, we need to update package managers such as Atom and anything else to point to the new repositories.

I would probably also create a centralized repository that contains a README.md and an issue tracker. This is where people could submit issues to make changes to the color scheme (if needed), talk about supporting new editors and such, etc. This is also where the color scheme and general information would be stored.

But really we need @zenorocha to agree to this all first since he owns it all.

**Comment by nesl247** [comment]
I would also suggest that at least a few other people get added as admins to the organization. That would help solve part of the issues from #149. While we have collaborators now, having other admins would mean that should @zenorocha not be available at all, other people can create repositories and such as needed.

**Comment by zenorocha** [comment]
Hey guys! I love that idea. I've contacted GitHub to see if we can get the `dracula` org ;D

**Comment by nesl247** [comment]
I'm assuming they won't remove someone's account, even if empty, to do that. So on the likely chance they won't, are you going to create a `dracula-theme` org?

**Comment by nesl247** [comment]
We should probably also try and merge in any open PRs that are good to go before the change. Once the change is made, we'd have to have all the PRs re-submitted against the appropriate repository.

**Comment by cbracco** [comment]
👍 Love this idea!

**Comment by zenorocha** [comment]
Let's see what happens, I got another organization already by contacting them.

I agree that we need to handle all issues/PRs before making any move.

**Comment by zenorocha** [comment]
Good news! I got the dracula name and added you guys as owners: https://github.com/dracula

**Comment by nesl247** [comment]
Is anyone in IRC or Slack or anything? It would probably be easier to coordinate the migration if we are.

**Comment by cbracco** [comment]
@zenorocha Awesome! I added an avatar for the organization that should suffice for the time being. 😸 

<img width="505" alt="screen shot 2016-05-18 at 3 22 05 pm" src="https://cloud.githubusercontent.com/assets/1480677/15372023/5d55debc-1d0c-11e6-8b47-4f6292ccae8e.png">

**Comment by cbracco** [comment]
@nesl247 should we create a slack org for dracula?

**Comment by nesl247** [comment]
Would be really useful. @zenorocha, mind creating one, or do you want one of us to?

**Comment by nesl247** [comment]
The site has been moved over. We just need to remove the CNAME file from the gh-pages branch here.

**Comment by JimmyMultani** [comment]
@zenorocha, are we allowed to transfer over themes separately now?

**Comment by zenorocha** [comment]
@cbracco yeah, let me create the slack org
@nesl247 roger that
@JimmyMultani let's close all issues/prs first

**Comment by Ulthes** [comment]
Hey, sorry guys I wasn't taking active part in conversation. It'll change once I complete some bigger portion of my project. I can move VS Code repo in the weekend. Plus I'm going to publish it on the Marketplace.

**Comment by nesl247** [comment]
I started a port for atom. Trying out the best way to migrate it. Not working quite as nicely as I thought because it wasn't all in the same directory.

**Comment by JimmyMultani** [comment]
@nesl247 Is it alright if I transfer the files over?

**Comment by nesl247** [comment]
@JimmyMultani Sure. Just do a force push and get rid of what is there.

**Comment by nesl247** [comment]
We can also just move this repository to the new organization so at least it's all in the right place. As we slowly migrate all the themes over we can remove them from this one. Eventually letting this repository become an issue tracker for approving new themes and such.

**Comment by nesl247** [comment]
@JimmyMultani Would it make sense to maybe just redo the Atom repo and just start from scratch? Wouldn't have any history then. That's what I was trying to do was to eliminate non-atom stuff from history.

**Comment by zenorocha** [comment]
Check this out http://slack.draculatheme.com

**Comment by heinst** [comment]
I can write a script that goes through the git log and prints commit ids for us to cherry pick

**Comment by nesl247** [comment]
@zenorocha Failed! Something has gone wrong. Please contact a system administrator.

**Comment by nesl247** [comment]
@heinst There's a tool called bfg to do cleanup. https://rtyley.github.io/bfg-repo-cleaner/

**Comment by cbracco** [comment]
@zenorocha @nesl247 failed for me too! got the same error message when submitting the form.

**Comment by nesl247** [comment]
I've moved most of the code over to the new repositories. The exceptions are projects that have open PRs/issues, and projects that have multiple versions such as visual-studio.

I'm not quite sure how everyone wants to handle the multiple versions. If we do them separately, it'll support package managers better, but then it is another repo for each version.

**Comment by zenorocha** [comment]
Try now http://slack.draculatheme.com/

**Comment by JimmyMultani** [comment]
@nesl247 I think we should keep the history if the old repo will be removed. At least then we can look back to see previous changes made to the atom files.

**Comment by nesl247** [comment]
@JimmyMultani Join us in slack.

**Comment by nesl247** [comment]
Going to close this as it's well underway.
