### ISSUE TITLE
Re-allow Chrome Dev Tools theme

### ISSUE THREAD

**Issue by jacksaunders** [zenorocha/dracula-theme#164]
@zenorocha i know you decided to abandon the chrome Dev tools theme due to the lack of public API, however i think that the [zero-base-themes](https://github.com/mauricecruz/zero-base-themes/) is well maintained enough to build a decent theme that is frequently updated. 

![image](https://cloud.githubusercontent.com/assets/1415692/15267370/82bd0b78-19ea-11e6-8bab-10d8b8fa29ef.png)
This is the Dracula tevtools theme i am using now which is generated from zero-base-themes

If you are happy to add it to the repo i am happy to keep on maintaining it / Submit it to the Chrome dev store etc

**Comment by nesl247** [comment]
@jacksaunders FYI your link to zero-base-themes is broken.

**Comment by jacksaunders** [comment]
Thanks @nesl247 fixed

**Comment by nesl247** [comment]
So I installed the theme. I would much prefer to the normal text to be white instead of yellow. The yellow text is extremely annoying to look at in my opinion.

**Comment by jacksaunders** [comment]
@nesl247 i havent put the theme up anywhere, not sure how you have installed it? Might be an old one, i will push my one up and let you have a look. Only the class and ID names are yellow in mine with the content muted

**Comment by nesl247** [comment]
@jacksaunders Got it from https://github.com/jacksaunders/dracula-chrome-dev-tools/commits/dracula-theme

**Comment by jacksaunders** [comment]
Ah ok that is the latest version then

**Comment by nesl247** [comment]
It isn't actually, that's the old branch from February. I wasn't getting it from master. I'm trying out the theme now from master.

**Comment by jacksaunders** [comment]
I think that will be similar, just updating the master not done much work on it since then

**Comment by nesl247** [comment]
Ah ok. Cause yeah, the screenshot you have in the OP here is what mine looks like. I'd love for all that yellow text to be white.

**Comment by jacksaunders** [comment]
Here it is white, i prefer it yellow as its closer to the syntax theme
![image](https://cloud.githubusercontent.com/assets/1415692/15272697/bf50acc2-1aab-11e6-8f12-7f62c7e1c135.png)

**Comment by jacksaunders** [comment]
for example here is the ATOM syntax theme

![image](https://cloud.githubusercontent.com/assets/1415692/15272705/2edc5bcc-1aac-11e6-86da-65def002264c.png)

**Comment by nesl247** [comment]
I much prefer it in white. That looks a million times better to me. The yellow is the color I hate in dracula to be honest. But that's another whole discussion. Better to keep it to match the ATOM theme. I'll probably just make the change locally and use the version I'd prefer :)

**Comment by zenorocha** [comment]
That sounds a good idea. I would love to use Dracula on DevTools again ;)

**Comment by jacksaunders** [comment]
Great, well it's almost good to go, going to wait on the outcome of #163 as I think it would be better as a seperate repo

**Comment by nesl247** [comment]
The yellow is even growing on me...

**Comment by zenorocha** [comment]
Since this a new theme I think we can start moving it to the new org.

https://github.com/dracula/chrome have fun @jacksaunders ;)

**Comment by zenorocha** [comment]
Closing this one for now since a new repo has been set up ;)
