### ISSUE TITLE
updated instructions for Installing using Atom

### ISSUE THREAD

**Issue by slothbear** [zenorocha/dracula-theme#166]
I couldn't find the source code for https://draculatheme.com/atom here or I'd fix this myself – but I'd also like to hear another Atom user (perhaps @JimmyMultani) validate this issue.

The instructions for _Install using Atom_ currently say:

1. Go to Atom -> Preferences...
2. Then select the Themes tab
3. Enter Dracula in the search box

The **Themes** tab has a search box, but only for installed themes. To install the theme, I needed to go to the **Install** tab, press the **Themes** button, then search (see attached image). So in my Atom (version 1.7.3), here are the steps I took. I've also made the search term more specific so the theme is the first result (it was the second result when searching for only "Dracula").

1. Go to Atom -> Preferences…
2. Then select the Install tab
3. Click on the Themes button (to the right of the search box)
4. Enter Dracula-theme in the search box

Thanks for a great theme!

![image](https://cloud.githubusercontent.com/assets/13285/15271011/5704c4fe-1a02-11e6-8d23-356cf903e969.png)

**Comment by nesl247** [comment]
If you want to submit a PR, look at the `gh-pages` branch and submit a PR against that. That's where the source code for the site is located.

**Comment by slothbear** [comment]
Thanks for the `site` tip @nesl247.  I've moved my proposed installation steps to #169.
