### ISSUE TITLE
Image in README does not exist

### ISSUE THREAD

**Issue by nesl247** [zenorocha/dracula-theme#167]
I'm not sure what the image was supposed to be (or I would have submitted a PR), but it is a broken image currently.

Specifically talking about the image in the install section.

**Comment by cbracco** [comment]
@nesl247 I think it was a screenshot of some arbitrary code showcasing the theme in action.

**Comment by nesl247** [comment]
Seems a weird place to put such a screenshot. Doesn't really belong in the installation section.
