### ISSUE TITLE
Markdown support in Sublime

### ISSUE THREAD

**Issue by surajsharma** [zenorocha/dracula-theme#178]
the colour coding in markdown is almost nonexistent, besides links, nothing is highlighted. this is in sublime text, am i doing something wrong or is there no differentiation in headings, bold, italic etc for the theme?

**Comment by defectivebit** [comment]
Code colouring is dependent on your editor; Dracula simply provides the colours that the editor uses in it's UI. If you want to change the code colouring, you need to edit the grammar file for your language, in this case Markdown. If you don't want to do that, Atom highlights headings, bold and italic text.

**Comment by surajsharma** [comment]
the theme does not provide scopes for markdown, those should be included.

**Comment by defectivebit** [comment]
@surajsharma Could you compile a list of the scopes that need to be colourised? [This StackOverflow](http://stackoverflow.com/questions/10834765/where-to-find-a-list-of-scopes-for-sublime2-or-textmate) seems to have the instructions but I'm not familiar with Sublime Text.

**Comment by surajsharma** [comment]
you can visit http://tmtheme-editor.herokuapp.com/ and see the different
scopes between Dracula.tmtheme and any other sublime theme which has the
scopes for markdown defined. right now i am just substituting Dracula
colours with my own custom theme, its not perfect but i would love Dracula
to come with official markdown support, at least on sublime. below is a
screenshot of how my hacked theme is looking:
http://puu.sh/oYUa8/8725226867.png

**Comment by nesl247** [comment]
Hi @surajsharma. If you wouldn't mind, please reopen this issue at https://github.com/dracula/textmate. We are in the process of completing a migration to an organization.

Thanks!
