### ISSUE TITLE
Sublime package includes two theme files

### ISSUE THREAD

**Issue by dsego** [zenorocha/dracula-theme#180]
Sublime package also includes the visual-studio-code theme file. Is this intended?

![screen shot 2016-05-20 at 15 41 54](https://cloud.githubusercontent.com/assets/578557/15429638/2e62f95e-1ea2-11e6-94c7-23a8b159212e.png)

If not intended, maybe adding *.no-sublime-package* to that sub-directory would help (just by looking at the docs, I actually know nothing about publishing sublime packages).
https://packagecontrol.io/docs/submitting_a_package#Step_5

**Comment by Ulthes** [comment]
I've already created pull-request for Package Control [HERE](https://github.com/wbond/package_control_channel/pull/5525). Dracula Theme has been moved to organization, this will solve this issue, since every theme has it's own repository.
