### ISSUE TITLE
large array in atom

### ISSUE THREAD

**Issue by dcrystalj** [zenorocha/dracula-theme#187]
not sure if it is dracula or atom problem but if i make large array (oneliner) in python,  only first few items gets colored: ![Image of array](http://pix.toile-libre.org/upload/original/1464267748.jpg)

**Comment by JimmyMultani** [comment]
Hey @dcrystalj, this is an issue related to Atom and how it parses tokens. It's a known bug and they are looking into it. You can check out one of the bugs [here](https://github.com/atom/atom/issues/1667).

**Comment by dcrystalj** [comment]
thank you
