### ISSUE TITLE
text spacing issues in jetbrains implementation

### ISSUE THREAD

**Issue by CestLou** [zenorocha/dracula-theme#188]
rubymine build: #RM-145.972
2016.1.1
OS X El Capitan v10.11.3

tried both downloading zip file and cloning repo. both bring me into a weird environment where the characters in any file type are either spaced out oddly or left in a state where it looks cramped and characters are squashed together (even though there are spaces technically present). I couldn't get a photo of the latter prior to me creating this ticket but if it arises again I will update.

flipping through the text in a document, the spaces appear. it seems to feel like a buggy feature, which if it is, I would love to know how to disable. haven't been able to find anything online about this. 

thanks in advance!

<img width="331" alt="screenshot 2016-05-26 16 08 34" src="https://cloud.githubusercontent.com/assets/7103027/15592918/6fbabdd8-235c-11e6-8bdb-a1508b8cb653.png">
<img width="200" alt="screenshot 2016-05-26 16 10 34" src="https://cloud.githubusercontent.com/assets/7103027/15592917/6fb9a29a-235c-11e6-9b17-17b2050e0ab3.png">

**Comment by joaoevangelista** [comment]
Which OS are you running on?

**Comment by joaoevangelista** [comment]
I tried to reproduce this with RM 145.972 running on JRE 1.8.0_77 on Windows 10, but no lucky. Can you please confirm that is not the font is causing this issue ?

**Comment by CestLou** [comment]
how strange, the default font the theme assigns (`source code pro`) breaks stuff. huh.

I'm running OS X El Capitan v10.11.3

your suggestion fixed it. thank you! 😁🏼

**Comment by joaoevangelista** [comment]
We are here to help! Indeed it is a problem from the Oracle JRE that caused a lot of trouble with fonts, at least the 2016.2 version of the platform will come with a custom version of OpenJdk bundle addressing font issues

**Comment by CestLou** [comment]
awesome. thanks again, really appreciate the prompt communication.

**Comment by CestLou** [comment]
hey there, sorry to trudge this up but just in case this goes overlooked (like it did for me) wanted you all to be aware!
rubymine has an embedded terminal that also has the `source code pro` font, and that is not updated when you update the general font type.
future reference perhaps? :)
