### ISSUE TITLE
exec illegal name in Python

### ISSUE THREAD

**Issue by albertosantini** [zenorocha/dracula-theme#37]
`exec` (between Default and ExecCommand) is in pink color (in SublimeText, Python syntax) because it is an `invalid.illegal.name.python`. I checked the scope with `ctrl+shit+alt+p`.

```
import Default

class ExecCommand(Default.exec.ExecCommand):
    def on_finished(self, proc):
# ...
```

I suppose the theme contains that definition and it seems the behaviour is correct.
Anyway I don't think the result is expected.

Any hint? (I have been using Dracula theme, but there is the same issue in the default themes).

Edit:
As wordaround I used importlib: now the python keyword exec is in a string.

```
# importlib - Only available for Python >= 2.7 or 3.x)
import importlib
defaultExec = importlib.import_module('Default.exec') 
# defaultExec = __import__('Default.exec', fromlist=[''])

class ExecCommand(defaultExec.ExecCommand):
#...
```

**Comment by zenorocha** [comment]
Closing since this is an outdated issue.
