### ISSUE TITLE
Instructions for vim are not correct…

### ISSUE THREAD

**Issue by evantravers** [zenorocha/dracula-theme#44]
It looks like if you just do what the instructions read for Vundle and :Bundle and :BundleInstall… it will download this repository to that folder, which it won't fit the normal folder structure vim expects, and thus won't install. If you want to install the Dracula theme, (as far as my feeble understanding) the folder has to be `~/.vim/dracula-theme/colors/dracula.vim`. Thoughts?

**Comment by abelncm** [comment]
[ Use with Vundle plugin ]
Use as said in the website, ex: Plugin "dracula/vim"
It'll download a folder with the name vim inside the bundle folder
Go inside vim folder (which vundle downloaded from dracula) cut the colors folder and paste it in ~/.vim
Then you can remove the vim folder
