### ISSUE TITLE
Add integration with JavaScript Next - SublimeText

### ISSUE THREAD

**Issue by albertosantini** [zenorocha/dracula-theme#47]
As feature request, it would be nice to have a sort of integration with the plugin [Javascript Next](https://sublime.wbond.net/packages/JavaScriptNext%20-%20ES6%20Syntax) for Sublime Text editor.

For instance the function parameters are not anymore in orange italic, but plain white.
I suppose the scope is different.

**Comment by zenorocha** [comment]
Closing since this is an outdated issue.
