### ISSUE TITLE
Python keywords not being highlighted

### ISSUE THREAD

**Issue by mdekauwe** [zenorocha/dracula-theme#76]
Hi,

for me the python keyword "self" isn't being highlighted?

thanks

**Comment by dciccale** [comment]
you can fix this by adding:

```css
.variable {
    color: #8be9fd;
}
```

this will highlight `self` with dracula's cyan.

I saw how default atom syntax themes where coloring the `self` python keyword and that is how it was targeted.

add the fix where you find convenient.

**Comment by zenorocha** [comment]
@JimmyMultani could you take a look?

**Comment by JimmyMultani** [comment]
Fixed in v1.2.4. :)
