### ISSUE TITLE
Deprecated selector

### ISSUE THREAD

**Issue by brunocoelho** [zenorocha/dracula-theme#78]
Hey @zenorocha, take a look at this deprecation note from atom.

![screen shot 2015-01-26 at 11 31 46 am](https://cloud.githubusercontent.com/assets/827445/5901164/0022292a-a54f-11e4-8965-53003e5d9a62.png)

**Comment by zenorocha** [comment]
Duplicated #77

**Comment by brunocoelho** [comment]
Indeed.

**Comment by zenorocha** [comment]
New version released: https://github.com/zenorocha/dracula-theme/releases/tag/v0.7.4

Thanks @rafaelstz!
