### ISSUE TITLE
Find/replace highlight is almost invisible in atom

### ISSUE THREAD

**Issue by hayes** [zenorocha/dracula-theme#79]
![screen shot 2015-02-03 at 3 12 58 pm](https://cloud.githubusercontent.com/assets/816527/6031797/3117c6b6-abb7-11e4-8afd-7596e100eb9e.png)

**Comment by ndgibson** [comment]
Here's a fix you can add to your `styles.less` file (type `stylesheet` into the command palette):

```
atom-text-editor::shadow .highlight.find-result .region {
  background: yellow;
}
atom-text-editor::shadow .highlight.current-result .region,
atom-text-editor::shadow .highlight.current-result ~ .highlight.selection .region {
  background: orange; // to distinguish from the other results
}
```

Source:
https://discuss.atom.io/t/how-to-change-find-and-replace-highlight-color/14750

**Comment by zenorocha** [comment]
Thanks a lot @hayes and @ndgibson, that really needs to be improved.

**Comment by Krajsnick** [comment]
I also noticed this, it's very hard to find what find-and-replace hightlights. I tried the fix from @ndgibs but that made background and foreground have same color, so couldn't see what it was hightlighting.

**Comment by jacksaunders** [comment]
Have fixed in pull request #130

**Comment by zenorocha** [comment]
@JimmyMultani could you close this once it's merged?

**Comment by JimmyMultani** [comment]
This fix has been merged. :)
