### ISSUE TITLE
Vim colors not as displayed in the preview

### ISSUE THREAD

**Issue by ding444** [zenorocha/dracula-theme#80]
For some reason I can't get the colors to look like the preview for VIM.  The background changes to a drab grey instead of the deep blue.  Here's a screenshot.

![preview image](http://cdn.deanc.me/image/1P101S0q3F2d/Voila_Capture%202015-02-07_09-22-11_PM.png)

I'm using iTerm2 (with the working Dracula theme), and `vim`.  I installed it via vundle as per the instructions, and even resorted to a manual installation of the theme into the `~/.vim/colors/` folder with the same results.  I've removed all other plugins and other settings in my `~/.vimrc` file to make sure there's nothing conflicting.

Does anyone have any idea what I'm doing wrong?

**Comment by zenorocha** [comment]
cc @cironunes

**Comment by cironunes** [comment]
Did you enable 256 colors in vim?

**Comment by ding444** [comment]
Yeah I've enabled it with `set t_Co=256`.  I've even gone as far as to revert to default by removing all settings and add them one by one to see if something trips it up.  Even with everything at default (OSX defaults) and with `set t_Co=256` I can't get it to work.

**Comment by tonatiuh** [comment]
Any news on this? I have the same issue, I'm using iterm2 and vim 7.4.488

**Comment by tonatiuh** [comment]
After doing some tests with the colors/dracula.vim (https://github.com/zenorocha/dracula-theme/blob/e011ccf2df9572fe53d058bf76dc63f1f794ed20/vim/colors/dracula.vim) file, I found that by removing the lines 39 and 57:

```
39: hi Normal ctermfg=231 ctermbg=235 cterm=NONE guifg=#f8f8f2 guibg=#282a36 gui=NONE
57: hi NonText ctermfg=59 ctermbg=236 cterm=NONE guifg=#3b3a32 guibg=#32343f gui=NONE
```

the colorschemes displays correct as seen in the preview page (http://zenorocha.github.io/dracula-theme/vim/ page).

@zenorocha do you know why could be that?
cc @ding444

**Comment by shkm** [comment]
Same issue here. Also using iTerm2, doesn't display correctly in either vim or neovim. Workaround works, so thanks for that, @tonatiuh!

**Comment by toogy** [comment]
Same issue here. Workaround worked too. (thanks @tonatiuh)

**Comment by toogy** [comment]
Well actually the colors still are not really the same. Some are more gray than violet. Don't know what's up...

**Comment by tonatiuh** [comment]
Yeah, I've noticed that it doesn't look exactly like the sample shared in http://zenorocha.github.io/dracula-theme/vim/. I'm not sure why is that.

Here is a sample of how it looks for me (running iTerm2 beta 3 with support for 24 bit colors) - still doesn't look like in the sample.

![in my computer](http://oi61.tinypic.com/1qsk8p.jpg)

vs

![sample shown in dracula site](http://zenorocha.github.io/dracula-theme/assets/img/screenshot-vim.png)

**Comment by toogy** [comment]
So there's no workaround. Can anyone fix this?

**Comment by tonatiuh** [comment]
Actually, I think the workaround is to use MacVim instead of Vim in the terminal. I was checking the colorscheme file, and I see expressions such as

```
ctermfg=17 ctermbg=231 cterm=NONE guifg=#282a36 guibg=#f8f8f0
```

That means, there is a color used in the terminal (ctermbg), and other more specific used for the GUI (guibg) - MacVim.

Not sure if with iTerm3 - which supports true colors - the colorscheme could be updated to be more accurate in the terminal version.

**Comment by tonatiuh** [comment]
Ok, I think I made it almost to the same as the preview image http://zenorocha.github.io/dracula-theme/vim/. Check the screenshot I took from my VIM

![local-vim-colors-improved](http://oi61.tinypic.com/4vmhjl.jpg)

To do that here is what I needed to update in the colorscheme file *dracula.vim*:

```
hi CursorLine ctermfg=NONE ctermbg=236 cterm=NONE guifg=NONE guibg=#2e3039 gui=NONE
hi Normal guifg=#f8f8f2 guibg=#1e1f29 gui=NONE
hi NonText guifg=#f8f8f2 guibg=#1e1f29 gui=NONE

hi TabLineFill  guifg=#333333 guibg=#1e1f29 gui=none
hi TabLine      guifg=#666666 guibg=#1e1f29 gui=none
hi TabLineSel   guifg=WHITE guibg=#1e1f29 gui=none
```

Some notes:

1.this will work only in the GUI mode (either mvim or neovim with [true colors](https://github.com/neovim/neovim/pull/2198)) since it's using hex colors and specifies settings only for "gui".
2. the hex colors I updated are not the ones shared in https://github.com/zenorocha/dracula-theme#color-palette, I'm not sure why, but the ones on that image are different -- so I picked the color codes directly from that image.
3. to get this to work in the terminal, I'm using iTerm2 beta 3 (Build 2.9.20151001) + Neovim (0.0.0-alpha+201509261553) with the `let $NVIM_TUI_ENABLE_TRUE_COLOR=1` option set.

cc @toogy

**Comment by toogy** [comment]
I'm using vim, not macvim/gvim/neovim because my vim runs in tmux on my company's servers.
I'll try to make it term-friendly when I'll have some time.

**Comment by ahmedelgabri** [comment]
Same here with iTerm2 beta, Tmux and Neovim all with true color enabled. @tonatiuh modifications works but I'll add 

```viml
hi LineNr ctermfg=246 ctermbg=None cterm=NONE guifg=#909194 guibg=None gui=NONE
```

To make it work nicely with gitgutter marks

Before:
<img width="1680" alt="screen shot 2015-10-31 at 00 33 00" src="https://cloud.githubusercontent.com/assets/63876/10860358/1d3fc542-7f67-11e5-9050-a0a11c0e387e.png">

After:
<img width="1680" alt="screen shot 2015-10-31 at 00 33 41" src="https://cloud.githubusercontent.com/assets/63876/10860360/26bad724-7f67-11e5-97f4-467589b07bc1.png">

**Comment by lowski** [comment]
I had the same problem - Terminal.app + vim. I'm using @sinakarimi fork and it background looks similar to those on the screenshots. Is this MR possible to merge?

**Comment by KevinSjoberg** [comment]
@zenorocha @cironunes any update on whether or not these changes will be merged with upstream?

**Comment by zenorocha** [comment]
We need a new maintainer for the Vim theme. Is there anyone interested on that?

**Comment by vinceskahan** [comment]
The @sinakarimi fork looks great on Yosemite in iterm2 for me too - the default seems to always revert the background to light even though it's sent dark in the .vimrc, which is odd.

Merge his tweaks !!!!

**Comment by sinakarimi** [comment]
@zenorocha I wouldn't mind maintaining the vim/emacs theme if you guys need help on it.

**Comment by nesl247** [comment]
Pinging @heinst the vim maintainer.

**Comment by heinst** [comment]
@sinakarimi sure! I have very little experience with creating vim themes and seems you have a lot more then I do CC: @zenorocha

**Comment by heinst** [comment]
Tweaks merged. Thanks @sinakarimi

**Comment by tgy** [comment]
I tried to install dracula again today and it still didn't work well.

For anyone who is interested, dracula is available in `base16` and it works perfectly with vim and neovim!

**Comment by Trollwut** [comment]
Also had this problem and could solve it

In my `~/.vimrc` I just added `color dracula` at the very last line.

Here is a [scrot of my vimrc](https://i.imgur.com/aqXUt0S.png)
