### ISSUE TITLE
missing "syntax-variables.less" stylesheet

### ISSUE THREAD

**Issue by ignism** [zenorocha/dracula-theme#81]
Some packages (including my Polymorph-UI) refer to `syntax-varables.less`. A stylesheet with basic color variables, I think there is a template for it on atom.io.

**Comment by zenorocha** [comment]
Interesting, I didn't know that. Would you like to send a PR based in our [color pallete](https://github.com/zenorocha/dracula-theme#color-palette)?

**Comment by jwnx** [comment]
I can confirm this issue. In my case, I'm using Nucleus Dark. There is a template, but I couldn't make it work.

**Comment by zenorocha** [comment]
Any news on this?

**Comment by haggen** [comment]
Could it be related to this:
![Dracula](https://cloud.githubusercontent.com/assets/270076/10856161/fb9598fc-7f2c-11e5-931e-21f88753842f.png)

See how the background outside the editor is one warm/brown-ish while the inside the purple-ish and the active tab is white. I love the palette but the UI should follow, as you can see with the default One Dark:
![One Dark](https://cloud.githubusercontent.com/assets/270076/10856219/57373382-7f2d-11e5-97e7-aeda27d16295.png)

**Comment by ainstushar** [comment]
Nucleus Dark UI with dracula theme produces some disastrous results. :( everything is white.

![screen shot 2015-11-17 at 6 14 46 pm](https://cloud.githubusercontent.com/assets/7689996/11227935/3eecf5a4-8d57-11e5-85e0-3fa396352855.jpg)
![screen shot 2015-11-17 at 6 16 18 pm](https://cloud.githubusercontent.com/assets/7689996/11227948/6037377e-8d57-11e5-9fa5-d561a82ca724.jpg)
![screen shot 2015-11-17 at 6 16 32 pm](https://cloud.githubusercontent.com/assets/7689996/11227949/6039d808-8d57-11e5-988b-1ef478083a36.jpg)

This is using One Dark UI:
![screen shot 2015-11-17 at 6 17 39 pm](https://cloud.githubusercontent.com/assets/7689996/11227971/85ec4f9a-8d57-11e5-918f-76ff9acb0545.jpg)

Seti UI beta looks normal:
![screen shot 2015-11-17 at 6 19 51 pm](https://cloud.githubusercontent.com/assets/7689996/11228012/d800f2fe-8d57-11e5-9a48-0c0d1f601537.jpg)

Does nucleus dark need to fix this issue or dracula? It's a shame that I can't use the best syntax theme with best UI theme together. :(

**Comment by JimmyMultani** [comment]
@zenorocha can you please take a look at the PR I made for this fix?

Thanks.

**Comment by JimmyMultani** [comment]
Hey @zenorocha, just another reminder that there are 2 pull requests that will fix this issue. Can you please look into them when you have the chance?

Thanks.

**Comment by dsifford** [comment]
@JimmyMultani Have you considered asking to be the maintainer of this repo? #149

**Comment by zenorocha** [comment]
@JimmyMultani has been added as the Atom theme maintainer. These issues will be fixed very soon. Sorry about that guys.

**Comment by JimmyMultani** [comment]
Should be fixed now. Thanks guys!

**Comment by zenorocha** [comment]
🎉
