### ISSUE TITLE
Apply color scheme to Man pages

### ISSUE THREAD

**Issue by cnluzhang** [zenorocha/dracula-theme#83]
Check the pic below.
![image](https://cloud.githubusercontent.com/assets/8707726/6163311/52657ce4-b2cb-11e4-8809-cdd420d62a3a.png)

The title of section is black, and the background is also dark color, so I can't identify them clearly.

Could you help me? Thanks.

**Comment by cnluzhang** [comment]
Hi, 
the problem will also appear in the 'brew' like pic below.
![image](https://cloud.githubusercontent.com/assets/8707726/6198581/ae1c289a-b446-11e4-968b-4d75e3250649.png)

![image](https://cloud.githubusercontent.com/assets/8707726/6198582/b5fce086-b446-11e4-8e77-aa9406c89dca.png)

Thx.

**Comment by cnluzhang** [comment]
also appear in vagrant...
![image](https://cloud.githubusercontent.com/assets/8707726/6201993/c5b16238-b507-11e4-8f9c-c02a7cb591e7.png)

**Comment by zenorocha** [comment]
We can't style a shell's inner command information. Only the shell script author is capable of adding colors and such thing.
