### ISSUE TITLE
Theme for Slack

### ISSUE THREAD

**Issue by zenorocha** [zenorocha/dracula-theme#87]
@quagliato created a theme for Slack and would be awesome to have it here as well. Could you send a PR with README and website entries?

**Comment by zenorocha** [comment]
http://pastebin.com/BLmAFxhx

**Comment by zenorocha** [comment]
Also submitted to https://github.com/paracycle/slackthemes/pull/10

**Comment by dennisreimann** [comment]
looks good :)

**Comment by nitinsurana** [comment]
https://draculatheme.com/slack/ - That's no theme, only the sidebar changes. The chat and every other thing is still white. There's already an in-built styling for sidebar.
