### ISSUE TITLE
SignColumn is not highlighted

### ISSUE THREAD

**Issue by admk** [zenorocha/dracula-theme#92]
Please see the attachment for an example.

![screen shot 2015-05-14 at 18 14 32](https://cloud.githubusercontent.com/assets/238821/7637344/2068b044-fa65-11e4-8b6a-527e60fbffcb.png)

**Comment by zenorocha** [comment]
Sorry @admk, could you be more specific? I'm no expert on vim so I look forward to a pull request.

**Comment by markwu** [comment]
```vim
hi SignColumn ctermfg=246 ctermbg=236 cterm=NONE guifg=#909194 guibg=#44475a gui=NONE
hi FoldColmun ctermfg=246 ctermbg=236 cterm=NONE guifg=#909194 guibg=#44475a gui=NONE
```
I add these two lines into dracula theme, you can see the difference.

Before:
![2016-05-07 11 37 42](https://cloud.githubusercontent.com/assets/196861/15093020/38cdc94a-14ad-11e6-9247-e995e3b31b58.png)

After:
![2016-05-07 11 38 08](https://cloud.githubusercontent.com/assets/196861/15093019/38cbdec8-14ad-11e6-9a09-78b525d93841.png)

I am not sure the color is a good choice or not, just for your reference.

`SignColumn`: Where is signs display ( like breakpoint, error signs)
`FoldColumn`: Where is fold display ( Like close/open folds)

Mark

**Comment by nesl247** [comment]
Pinging @heinst the vim maintainer.

**Comment by heinst** [comment]
Thanks @markwu
