### ISSUE TITLE
Emacs love?

### ISSUE THREAD

**Issue by chalmagean** [zenorocha/dracula-theme#93]
Do you guys plan on having a theme for Emacs?

-- Cezar

**Comment by film42** [comment]
:+1: I set out to write dracula-theme for emacs port, but got crazy busy. Would the maintainers be willing to accept the contribution if I open a PR?

**Comment by Naomarik** [comment]
@film42 did you end up finishing this? Would love to use it.

**Comment by film42** [comment]
@Naomarik I'll finish it up this weekend :)

**Comment by sickill** [comment]
+1

**Comment by film42** [comment]
Ok everyone. Here's what I currently have:

![image](https://cloud.githubusercontent.com/assets/1043908/8268365/c4928652-1740-11e5-92c4-2486485cd427.png)

![image](https://cloud.githubusercontent.com/assets/1043908/8268366/da724e58-1740-11e5-9ffa-77976450a6c3.png)

![image](https://cloud.githubusercontent.com/assets/1043908/8268380/26144f78-1741-11e5-9335-cfa7f13e690e.png)


Javascript could probably use a little bit more love, but I don't want to get into custom `font-lock`s for that mode.


If everyone is happy, I'll make a PR for this.

**Comment by film42** [comment]
PS: Here's the current gist: https://gist.github.com/film42/6d45ae89bfa2c92c4717

**Comment by chalmagean** [comment]
Cool, this looks great

**Comment by chalmagean** [comment]
Thank you @film42

**Comment by zenorocha** [comment]
Is there anyone interested in sending a PR and maintain that?

**Comment by film42** [comment]
I'll do it. Just waiting to hear from you :)

**Comment by zenorocha** [comment]
Sorry about the delay :)

**Comment by film42** [comment]
![screen shot 2015-07-13 at 10 37 30 pm](https://cloud.githubusercontent.com/assets/1043908/8666519/d4bc2d04-29af-11e5-9bb4-1c295c55728f.png)

REAME screenshot (upcoming PR)

**Comment by tkaczu** [comment]
Hi,

Could anybody please merge this emacs theme to the repo?

**Comment by avelino** [comment]
+1

**Comment by film42** [comment]
I'll merge master in to clean this up later today.

**Comment by film42** [comment]
Woo hoo, this got merged in. This issue can be closed now.

**Comment by zenorocha** [comment]
I'm sorry it took so long to merge this :/

See:
* http://zenorocha.github.io/dracula-theme/emacs
* https://github.com/zenorocha/dracula-theme/releases/tag/v1.0.0

Thank you so much everyone involved :)
